basePath: '{{.BasePath}}'
definitions:
  model.UserData:
    properties:
      company:
        example: "5687"
        type: string
      password:
        example: Baba
        type: string
      user:
        example: "1234"
        type: string
    required:
    - company
    - password
    - user
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: "1.0"
paths:
  /v1/watcher/checkin:
    post:
      consumes:
      - application/json
      description: get request to perform checkin
      operationId: checkin
      parameters:
      - description: User Data
        in: body
        name: user_data
        required: true
        schema:
          $ref: '#/definitions/model.UserData'
          type: object
      - description: Max delay in minutes until request is sent (random)
        in: query
        name: max_delay
        type: string
      produces:
      - application/json
      summary: Perform checkin via timewatch.co.il
      tags:
      - Watcher
  /v1/watcher/checkout:
    post:
      consumes:
      - application/json
      description: get request to perform checkout
      operationId: checkout
      parameters:
      - description: User Data
        in: body
        name: user_data
        required: true
        schema:
          $ref: '#/definitions/model.UserData'
          type: object
      - description: Max delay in minutes until request is sent (random)
        in: query
        name: max_delay
        type: string
      produces:
      - application/json
      summary: Perform checkout via timewatch.co.il
      tags:
      - Watcher
swagger: "2.0"
