# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.1.0
workflows:
  main:
    jobs:
      - build
      - gke/publish-and-rollout-image:
          context: watchmen
          deployment: watchmen
          image: watchmen
          container: watchmen

