version: 2
orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.4
jobs:
  deploy:
    executor: gcp-gcr/default
    steps:
      - run:
          name: setup  gcloud
          command: |
            if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            $SUDO gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            $SUDO gcloud --quiet config set project $GOOGLE_PROJECT_ID
            $SUDO gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud container clusters get-credentials standard-cluster-1 --zone us-central1-a --project the-full-stack
      - run:
          name: setup kube-ctl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && sudo chmod +x ./kubectl || chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin || mv ./kubectl /usr/local/bin
      - run:
          name: update watchmen
          command: |
            kubectl set image deployment.extensions/watchmen watchmen=gcr.io/the-full-stack/watchmen:$CIRCLE_SHA1 --record=true

workflows:
  main:
    jobs:
      - gcp-gcr/build_and_push_image:
          image: watchmen
          tag: $CIRCLE_SHA1
      - deploy:
          requires:
            - gcp-gcr/build_and_push_image