version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.4
jobs:
  build:
    executor: gcp-gcr/default
    steps:
#      - checkout # check out the code in the project directory
      - run: gcloud container clusters get-credentials standard-cluster-1 --zone us-central1-a --project the-full-stack

workflows:
  main:
    jobs:
#      - gcp-gcr/build_and_push_image:
#          image: watchmen
#          tag: latest
      - build:
#          requires:
#            - gcp-gcr/build_and_push_image