version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.4
workflows:
  main:
    jobs:
      - gcp-gcr/build_and_push_image:
          image: watchmen
          tag: latest
      - steps:
        - run: gcloud container clusters get-credentials standard-cluster-1
        - run: echo BABA