version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.4
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - echo BABA
workflows:
  main:
    jobs:
      - gcp-gcr/build_and_push_image:
          image: watchmen
          tag: latest
      - deploy: