version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.4
jobs:
  build:
    executor: gcp-gcr/default
    steps:
#      - checkout # check out the code in the project directory
      - run: if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: $SUDO gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: $SUDO gcloud --quiet config set project $GOOGLE_PROJECT_ID
      - run: $SUDO gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
      - run: gcloud container clusters get-credentials standard-cluster-1 --zone us-central1-a --project the-full-stack
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/latest/bin/linux/amd64/kubectl && sudo chmod +x ./kubectl || chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin || mv ./kubectl /usr/local/bin
      - run: kubectl set image deployment.extensions/watchmen watchmen=gcr.io/the-full-stack/watchmen:latest --record=true

workflows:
  main:
    jobs:
      - gcp-gcr/build_and_push_image:
          image: watchmen
          tag: latest
      - build:
          requires:
            - gcp-gcr/build_and_push_image