version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@1.0.0
workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build_and_push_image_using_remote_docker:
          image: watchmen
          tag: latest