// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-03-08 19:07:29.631084 +0200 IST m=+0.020576562

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/watcher/checkin/{employee_id}/{password}": {
            "get": {
                "description": "get request to perform checkin",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watcher"
                ],
                "summary": "Perform Checkin to timewatch.co.il",
                "operationId": "checkin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "employee_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Employee Password",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/v1/watcher/checkout/{employee_id}/{password}": {
            "get": {
                "description": "get request to perform checkout",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Watcher"
                ],
                "summary": "Perform Checkout to timewatch.co.il",
                "operationId": "checkout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "employee_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Employee Password",
                        "name": "password",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
